apiVersion: v1
kind: Namespace
metadata:
  name: web-app
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: web-app-quota
  namespace: web-app
spec:
  hard:
    requests.cpu: "10m"
    requests.memory: 1Gi
    limits.cpu: "20m"
    limits.memory: 2Gi
